apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-app
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: web-ui-app
  replicas: 1
  template:
    metadata:
      labels:
        app: web-ui-app
    spec:
      containers:
        - name: web-ui-container
          image: {{IMAGE_NAME}}
          imagePullPolicy: Always
          ports:
            - name: web-ui-port
              containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  namespace: {{NAMESPACE}}
  labels:
    app: web-ui-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: web-ui-port
      protocol: TCP
  selector:
    app: web-ui-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ui
  namespace: {{NAMESPACE}}
spec:
  rules:
    - host: {{ENV_SUFFIX}}mydna.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-ui-service
                port:
                  number: 80
